typeset -g POWERLEVEL9K_BACKGROUND='#1e1e2e'

typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#cba6f7'

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#f38ba8'

typeset -g POWERLEVEL9K_DIR_FOREGROUND='#89b4fa'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#74c7ec'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#b4befe'

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#fab387'

typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#a6e3a1'

typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#f38ba8'

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#bac2de'

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#89dceb'

typeset -g POWERLEVEL9K_DIRENV_FOREGROUND='#f9e2af'

typeset -g POWERLEVEL9K_ASDF_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_ASDF_RUBY_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_ASDF_NODEJS_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_ASDF_RUST_FOREGROUND='#fab387'
typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_ASDF_LUA_FOREGROUND='#94e2d5'
typeset -g POWERLEVEL9K_ASDF_JAVA_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_ASDF_PERL_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_ASDF_ERLANG_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND='#89b4fa'
typeset -g POWERLEVEL9K_ASDF_PHP_FOREGROUND='#b4befe'
typeset -g POWERLEVEL9K_ASDF_HASKELL_FOREGROUND='#fab387'
typeset -g POWERLEVEL9K_ASDF_JULIA_FOREGROUND='#a6e3a1'

typeset -g POWERLEVEL9K_YAZI_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_RANGER_FOREGROUND='#f9e2af'

typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND='#89b4fa'

typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND='#f38ba8'

typeset -g POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_VI_MODE_VISUAL_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_VI_MODE_OVERWRITE_FOREGROUND='#fab387'
typeset -g POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='#89b4fa'

typeset -g POWERLEVEL9K_RAM_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_SWAP_FOREGROUND='#cba6f7'

typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND='#f38ba8'

typeset -g POWERLEVEL9K_TODO_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND='#89b4fa'

typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND='#fab387'

typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND='#fab387'

typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND='#fab387'
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#cba6f7'

typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_PYENV_FOREGROUND='#89dceb'

typeset -g POWERLEVEL9K_NODENV_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_NVM_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_NODEENV_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND='#a6e3a1'

typeset -g POWERLEVEL9K_GOENV_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND='#89dceb'

typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND='#fab387'

typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND='#f9e2af'

typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND='#b4befe'

typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND='#89dceb'

typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND='#fab387'
typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_AZURE_OTHER_FOREGROUND='#89b4fa'
typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND='#89dceb'

typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND='#89dceb'
typeset -g POWERLEVEL9K_IP_FOREGROUND='#89b4fa'
typeset -g POWERLEVEL9K_PROXY_FOREGROUND='#74c7ec'

typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='#f9e2af'

typeset -g POWERLEVEL9K_WIFI_FOREGROUND='#89dceb'

typeset -g POWERLEVEL9K_TIME_FOREGROUND='#b4befe'

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#313244'
